apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  # Development settings - lower retention and resources
  retention: 7d
  retentionSize: 10GB

  # Storage for dev
  storageSpec:
    volumeClaimTemplate:
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 15Gi

  # Lower resources for dev
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi

  # Single replica for dev
  replicas: 1

  # Faster scrape interval for dev
  scrapeInterval: 15s
  evaluationInterval: 15s

  # External labels
  externalLabels:
    cluster: main
    environment: dev