---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    app.kubernetes.io/name: prometheus
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`prometheus.nexus.local`)
      priority: 20
      services:
        - name: prometheus-prometheus
          port: 9090
      middlewares:
        - name: security-headers
          namespace: traefik
  tls:
    secretName: prometheus-tls

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus-tls
  namespace: monitoring
spec:
  secretName: prometheus-tls
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
  dnsNames:
    - prometheus.nexus.local
  usages:
    - digital signature
    - key encipherment

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus-http
  namespace: monitoring
  labels:
    app.kubernetes.io/name: prometheus
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`prometheus.nexus.local`)
      priority: 20
      services:
        - name: prometheus-prometheus
          port: 9090
      middlewares:
        - name: redirect-https
          namespace: traefik