---
# Daily full cluster backup (all namespaces except excluded)
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: daily-full-backup
  namespace: velero
spec:
  # Run daily at 2 AM
  schedule: "0 2 * * *"
  template:
    includedNamespaces:
      - "*"
    excludedNamespaces:
      - kube-system
      - kube-public
      - kube-node-lease
    includeClusterResources: true
    ttl: 720h  # 30 days retention
    storageLocation: default
    volumeSnapshotLocations:
      - default
    defaultVolumesToFsBackup: true

---
# Hourly backup of critical namespaces
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: hourly-critical-backup
  namespace: velero
spec:
  # Run every hour
  schedule: "@hourly"
  template:
    includedNamespaces:
      - argocd
      - monitoring
      - cert-manager
    includeClusterResources: false
    ttl: 168h  # 7 days retention
    storageLocation: default
    defaultVolumesToFsBackup: true

---
# Weekly backup of platform configuration
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: weekly-platform-backup
  namespace: velero
spec:
  # Run weekly on Sunday at 3 AM
  schedule: "0 3 * * 0"
  template:
    includedNamespaces:
      - traefik
      - argocd
      - cert-manager
      - sealed-secrets
      - monitoring
      - velero
    includeClusterResources: true
    ttl: 2160h  # 90 days retention
    storageLocation: default
    volumeSnapshotLocations:
      - default
    defaultVolumesToFsBackup: true

---
# Monthly full cluster backup (long-term retention)
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: monthly-full-backup
  namespace: velero
spec:
  # Run on the 1st of each month at 4 AM
  schedule: "0 4 1 * *"
  template:
    includedNamespaces:
      - "*"
    excludedNamespaces:
      - kube-system
      - kube-public
      - kube-node-lease
    includeClusterResources: true
    ttl: 8760h  # 365 days (1 year) retention
    storageLocation: default
    volumeSnapshotLocations:
      - default
    defaultVolumesToFsBackup: true

---
# Backup of persistent volumes only
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: daily-pv-backup
  namespace: velero
spec:
  # Run daily at 1 AM
  schedule: "0 1 * * *"
  template:
    includedResources:
      - persistentvolumes
      - persistentvolumeclaims
    includeClusterResources: false
    ttl: 168h  # 7 days retention
    storageLocation: default
    volumeSnapshotLocations:
      - default
    defaultVolumesToFsBackup: true

---
# Example: Namespace-specific backup (production apps)
# apiVersion: velero.io/v1
# kind: Schedule
# metadata:
#   name: production-apps-backup
#   namespace: velero
# spec:
#   schedule: "0 */6 * * *"  # Every 6 hours
#   template:
#     includedNamespaces:
#       - production
#     labelSelector:
#       matchLabels:
#         environment: production
#     includeClusterResources: false
#     ttl: 336h  # 14 days retention
#     storageLocation: default
#     defaultVolumesToFsBackup: true

---
# Example: Backup with hooks (pre/post backup scripts)
# apiVersion: velero.io/v1
# kind: Schedule
# metadata:
#   name: database-backup-with-hooks
#   namespace: velero
# spec:
#   schedule: "0 3 * * *"  # Daily at 3 AM
#   template:
#     includedNamespaces:
#       - databases
#     labelSelector:
#       matchLabels:
#         app: postgresql
#     hooks:
#       resources:
#         - name: postgresql-backup-hook
#           includedNamespaces:
#             - databases
#           labelSelector:
#             matchLabels:
#               app: postgresql
#           pre:
#             - exec:
#                 container: postgresql
#                 command:
#                   - /bin/bash
#                   - -c
#                   - pg_dumpall > /tmp/backup.sql
#                 onError: Fail
#                 timeout: 5m
#     ttl: 720h  # 30 days retention
#     storageLocation: default
#     defaultVolumesToFsBackup: true